site_name: ProtoSmasher Documentation
repo_name: 'ProtoSmasher-Docs'
repo_url: 'https://github.com/Infernal-Software/ProtoSmasher-Docs'

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

markdown_extensions:
  - codehilite
  - admonition